#!/bin/sh

if [ $# -ne 2 ]; then
  echo "usage: $0 path/to/probes.d path/to/output.h"
  exit 1
fi

TEMPFILE=$(mktemp)

cleanup() {
  rm -f "$TEMPFILE"
}

trap cleanup EXIT

probenames() {
  sed 's/^\s*probe \(.*\)(.*/\1/;tx;d;:x' "$1"
}

toupper() {
  tr '[:lower:]' '[:upper:]'
}

echo "// Autogenerated by $0" > "$TEMPFILE"
echo "// do not edit by hand" >> "$TEMPFILE"

for probe in $(probenames "$1" | toupper); do
  printf "#define PROBE_%s_ENABLED() 0\n" "$probe" >> "$TEMPFILE"
  printf "#define PROBE_%s(...)\n" "$probe" >> "$TEMPFILE"
done

if ! cmp -s "$TEMPFILE" "$2"; then
  mv "$TEMPFILE" "$2"
fi
