#!/bin/sh
#
# Generate a probes.h file from probes.d. This script is invoked by make when
# SystemTap support is disabled. The make target depends on probes.d, so this
# script is only executed when probes.d actually changes.

if [ $# -ne 2 ]; then
  echo "Usage: $0 path/to/probes.d path/to/probes.h"
  exit 1
fi

# Where we'll put temporary data.
TEMPFILE=$(mktemp)
cleanup() { rm -f "$TEMPFILE"; }
trap cleanup EXIT

# Sed is fun, easy, and portable!
probenames() { sed 's/^\s*probe \(.*\)(.*/\1/;tx;d;:x' "$1"; }
toupper() { sed 'y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/'; }

# Generate the tempfile.
{
  echo "// This file was auto-generated by $0 from $1"
  echo "// For more information about this file, see doc/systemtap.md"
  echo ""
  echo "#ifndef BITCOIN_PROBES_H"
  echo "#define BITCOIN_PROBES_H"
  echo ""

  # The ENABLED() probe evaluates to 0, and the probe itself becomes ((void) 0),
  # which avoids compiler warnings about a missing "if" body. Code for these
  # branches will be eliminated by the compiler.
  for probe in $(probenames "$1" | toupper); do
    echo "#define PROBE_${probe}_ENABLED() 0"
    echo "#define PROBE_${probe}(...) ((void) 0)"
    echo
  done

  echo "#endif  // BITCOIN_PROBES_H"
} > "$TEMPFILE"

# If this file differs from probes.h, replace it.
if ! cmp -s "$TEMPFILE" "$2"; then
  mv "$TEMPFILE" "$2"
fi
