// Copyright (c) 2018 The Bitcoin Core developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#ifndef BITCOIN_PROBES_H
#define BITCOIN_PROBES_H

#include <config/bitcoin-config.h>

#ifdef WITH_PROBES
// This file is automatically generated by dtrace(1), and defines the probes
// themselves (and macros to check if they're enabled).
#include <probes_impl.h>
#else
// Without probes these should all be no-ops.
static inline void BITCOIN_CACHE_FLUSH_START(size_t arg0) {}
static inline void BITCOIN_CACHE_FLUSH_END() {}
static inline void BITCOIN_CACHE_HIT() {}
static inline void BITCOIN_CACHE_MISS() {}
#endif // WITH_PROBES
#endif // BITCOIN_PROBES_H
